{% set template_info = {
  'version': '1.1.0',
  'adapted_from': 'SWITCH_BASELINE_v1.0.0',
  'project': 'SM1069',
  'doc_id': 'cNETHW System Installation and Configuration',
  'template_name': 'INTERFACE_BASELINE',
  'linked_templates': 'OSPF_NETWORK'
} %}
mdd_tags:
  - vlan
mdd_data:
  config:
    tailf-ned-cisco-ios:interface:
      Vlan:
{% for vlan in config_vars.vlans %}
      - name: {{ vlan.name }}
        description: {{ vlan.description }}
        ip:
          no-address:
            address: false
{% for ospf in config_vars.router.ospf %}
{% if 'vlan' + vlan.vlan|string == ospf.interface %}
          ospf:
            authentication:
              key-chain: {{ ospf.key_chain}}
            message-digest-key:
            - id: 1
              md5:
                type: '7'
                secret: {{ ospf.ospf_key }}
{% endif %}
{% endfor %}
{% endfor %}
