---
mdd_data:
  config:
    tailf-ned-cisco-ios:tailfned:
      police: cirmode
    tailf-ned-cisco-ios:version: '17.9'
    tailf-ned-cisco-ios:service:
      conf: {}
      timestamps: {}
      call-home:
        - null
    tailf-ned-cisco-ios:login:
      on-success: {}
    tailf-ned-cisco-ios:platform:
      console: virtual
      punt-keepalive:
        disable-kernel-core: true
      qfp:
        utilization:
          monitor:
            load: 80
    tailf-ned-cisco-ios:aaa:
      new-model:
        - null
      authentication:
        login:
          - name: default
            local:
              - null
      authorization:
        exec:
          - name: default
            local:
              - null
            none:
              - null
      session-id: common
    tailf-ned-cisco-ios:call-home:
      contact-email-addr: sch-smart-licensing@cisco.com
      profile:
        - name: CiscoTAC-1
          active: true
          reporting:
            smart-licensing-data: true
          destination:
            transport-method:
              http:
                - null
    tailf-ned-cisco-ios:iox: {}
    tailf-ned-cisco-ios:ip:
      tcp:
        window-size: 8192
      ssh:
        rsa:
          keypair-name: ssh-key
        pubkey-chain:
          username:
            - name: ec2-user
              key-hash:
                - key-type: ssh-rsa
                  key-name: 1A139C85949B0FCC56B308A2062710E0
                  key-comment: ec2-user
      scp:
        server:
          enable:
            - null
      forward-protocol:
        nd:
          - null
      http: {}
    tailf-ned-cisco-ios:ipv6:
      unicast-routing:
        - null
    tailf-ned-cisco-ios:subscriber:
      templating: true
    tailf-ned-cisco-ios:multilink:
      bundle-name: authenticated
    tailf-ned-cisco-ios:username:
      - name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        privilege: 15
        password:
          type: '7'
          secret: 00071A150754
      - name: ec2-user
        privilege: 15
    tailf-ned-cisco-ios:redundancy: {}
    tailf-ned-cisco-ios:vtp:
      version: 1
      mode: server
    tailf-ned-cisco-ios:crypto:
      pki:
        trustpoint:
          - id: SLA-TrustPoint
            enrollment:
              pkcs12:
                - null
            revocation-check:
              - crl
          - id: TP-self-signed-2988619814
            enrollment:
              selfsigned:
                - null
            subject-name: cn=IOS-Self-Signed-Certificate-2988619814
            revocation-check:
              - none
            rsakeypair:
              key-label: TP-self-signed-2988619814
        certificate:
          chain:
            - name: SLA-TrustPoint
              certificate:
                - serial: '01'
                  cert-type: ca
                  cert: "  30820321 30820209 A0030201 02020101 300D0609 2A864886 F70D0101\
                    \ 0B050030 \r\n  32310E30 0C060355 040A1305 43697363 6F312030\
                    \ 1E060355 04031317 43697363 \r\n  6F204C69 63656E73 696E6720\
                    \ 526F6F74 20434130 1E170D31 33303533 30313934 \r\n  3834375A\
                    \ 170D3338 30353330 31393438 34375A30 32310E30 0C060355 040A1305\
                    \ \r\n  43697363 6F312030 1E060355 04031317 43697363 6F204C69\
                    \ 63656E73 696E6720 \r\n  526F6F74 20434130 82012230 0D06092A\
                    \ 864886F7 0D010101 05000382 010F0030 \r\n  82010A02 82010100\
                    \ A6BCBD96 131E05F7 145EA72C 2CD686E6 17222EA1 F1EFF64D \r\n \
                    \ CBB4C798 212AA147 C655D8D7 9471380D 8711441E 1AAF071A 9CAE6388\
                    \ 8A38E520 \r\n  1C394D78 462EF239 C659F715 B98C0A59 5BBB5CBD\
                    \ 0CFEBEA3 700A8BF7 D8F256EE \r\n  4AA4E80D DB6FD1C9 60B1FD18\
                    \ FFC69C96 6FA68957 A2617DE7 104FDC5F EA2956AC \r\n  7390A3EB\
                    \ 2B5436AD C847A2C5 DAB553EB 69A9A535 58E9F3E3 C0BD23CF 58BD7188\
                    \ \r\n  68E69491 20F320E7 948E71D7 AE3BCC84 F10684C7 4BC8E00F\
                    \ 539BA42B 42C68BB7 \r\n  C7479096 B4CB2D62 EA2F505D C7B062A4\
                    \ 6811D95B E8250FC4 5D5D5FB8 8F27D191 \r\n  C55F0D76 61F9A4CD\
                    \ 3D992327 A8BB03BD 4E6D7069 7CBADF8B DF5F4368 95135E44 \r\n \
                    \ DFC7C6CF 04DD7FD1 02030100 01A34230 40300E06 03551D0F 0101FF04\
                    \ 04030201 \r\n  06300F06 03551D13 0101FF04 05300301 01FF301D\
                    \ 0603551D 0E041604 1449DC85 \r\n  4B3D31E5 1B3E6A17 606AF333\
                    \ 3D3B4C73 E8300D06 092A8648 86F70D01 010B0500 \r\n  03820101\
                    \ 00507F24 D3932A66 86025D9F E838AE5C 6D4DF6B0 49631C78 240DA905\
                    \ \r\n  604EDCDE FF4FED2B 77FC460E CD636FDB DD44681E 3A5673AB\
                    \ 9093D3B1 6C9E3D8B \r\n  D98987BF E40CBD9E 1AECA0C2 2189BB5C\
                    \ 8FA85686 CD98B646 5575B146 8DFC66A8 \r\n  467A3DF4 4D565700\
                    \ 6ADF0F0D CF835015 3C04FF7C 21E878AC 11BA9CD2 55A9232C \r\n \
                    \ 7CA7B7E6 C1AF74F6 152E99B7 B1FCF9BB E973DE7F 5BDDEB86 C71E3B49\
                    \ 1765308B \r\n  5FB0DA06 B92AFE7F 494E8A9E 07B85737 F3A58BE1\
                    \ 1A48A229 C37C1E69 39F08678 \r\n  80DDCD16 D6BACECA EEBC7CF9\
                    \ 8428787B 35202CDC 60E4616A B623CDBD 230E3AFB \r\n  418616A9\
                    \ 4093E049 4D10AB75 27E86F73 932E35B5 8862FDAE 0275156F 719BB2F0\
                    \ \r\n  D697DF7F 28\r\n"
            - name: TP-self-signed-2988619814
              certificate:
                - serial: '01'
                  cert-type: self-signed
                  cert: "  30820330 30820218 A0030201 02020101 300D0609 2A864886 F70D0101\
                    \ 05050030 \r\n  31312F30 2D060355 04031326 494F532D 53656C66\
                    \ 2D536967 6E65642D 43657274 \r\n  69666963 6174652D 32393838\
                    \ 36313938 3134301E 170D3233 31323037 32323331 \r\n  30375A17\
                    \ 0D333331 32303632 32333130 375A3031 312F302D 06035504 03132649\
                    \ \r\n  4F532D53 656C662D 5369676E 65642D43 65727469 66696361\
                    \ 74652D32 39383836 \r\n  31393831 34308201 22300D06 092A8648\
                    \ 86F70D01 01010500 0382010F 00308201 \r\n  0A028201 01009ED3\
                    \ F3960FCC 0314366A 7168FF10 28222878 CFF550DF A48E7648 \r\n \
                    \ 7B19E07C 52E12021 86C7E420 01DFCE22 95AB4F70 5875A4AD F0AA046E\
                    \ 609F119B \r\n  2D668364 9CD75F9C 29B0A1C4 CD7226E6 12BC6EBC\
                    \ 1AAE356D E3ED8557 44BDB4FF \r\n  42F22C4C D54F556A BF3E44AF\
                    \ 267887FB 710270B3 0984BA03 07211E96 A43A0B08 \r\n  D0D71F2C\
                    \ FC7A59EF EE69DE0F E56491A4 BE69CB21 7A12B546 6C733722 6E6C9E82\
                    \ \r\n  E990575F 44786F1C 42AC8DC9 BD29920C 2707031E CA793B02\
                    \ 39F3C3B0 AA4D4088 \r\n  15FA49AA CF3E714E 30686EFF 9D65A5F3\
                    \ AD441AF3 33D3D231 432E08A1 051A3AFB \r\n  5AE5B096 24BE51EE\
                    \ 7ABD6630 78676741 A499AE24 12879C94 4B75FF37 467666AA \r\n \
                    \ FDE1FC1E 38090203 010001A3 53305130 0F060355 1D130101 FF040530\
                    \ 030101FF \r\n  301F0603 551D2304 18301680 14DCC53B E15B672E\
                    \ 0E006391 F0645A5D 59EB0130 \r\n  88301D06 03551D0E 04160414\
                    \ DCC53BE1 5B672E0E 006391F0 645A5D59 EB013088 \r\n  300D0609\
                    \ 2A864886 F70D0101 05050003 82010100 58EF5BF5 DD014DC6 957F44FC\
                    \ \r\n  9C7A06F8 7B8DBFF8 C7F10916 1CF2A295 AA7B6AAE 2CBD2E59\
                    \ 8B2C895A 95BFF455 \r\n  F788FFB8 728CB502 0D7C484D AABF6F9E\
                    \ F26EE59E 81C5092C 1F91FAD7 13A75D01 \r\n  5EB2DD4E D86A3DE1\
                    \ 79AA58B5 C46BD085 4D61E2F7 F78AA768 B0F23FF9 B8C714B6 \r\n \
                    \ C2D5ED96 D4CC8A01 62100B2F 5A20418E 91404647 15752E7A 99FD1553\
                    \ D7870808 \r\n  39944080 E6F7273F F08A0E5B 044B54E6 5077B068\
                    \ 7F2E3E19 7DAE18AE 892B5CCE \r\n  AF410542 E553004E 607152BC\
                    \ AA6F04B4 3D1FDD7A 89149270 85127F14 A6F8B9F2 \r\n  6611795D\
                    \ 7E2DE0BF D8BB2088 99C9D043 16C33DBF 5C9CCBB5 CCF5E752 9CF6EA48\
                    \ \r\n  F08BFAA9 805B0AEC 4998491F 356175EE FD859F7C\r\n"
    tailf-ned-cisco-ios:interface:
      Tunnel:
        - name: 2
          ip:
            address: {}
          tunnel: {}
        - name: 20
          ip:
            address: {}
          tunnel: {}
      GigabitEthernet:
        - name: '1'
          negotiation: {}
          ip:
            address:
              dhcp: {}
            nat: {}
          ipv6:
            address:
              dhcp: {}
            enable:
              - null
            nd:
              autoconfig:
                default-route:
                  - null
        - name: '2'
          negotiation: {}
          ip:
            no-address:
              address: false
    tailf-ned-cisco-ios:control-plane: {}
    tailf-ned-cisco-ios:line:
      console:
        - first: '0'
          stopbits: '1'
      aux:
        - first: '0'
      vty:
        - first: 0
          last: 4
          transport:
            input:
              - ssh
        - first: 5
          last: 20
          transport:
            input:
              - ssh
    tailf-ned-cisco-ios:logging:
      buffered: {}
      console: {}
      monitor: {}
    tailf-ned-cisco-ios:diagnostic:
      bootup:
        level: minimal
    tailf-ned-cisco-ios:router:
      ospf:
        - id: 10
    tailf-ned-cisco-ios:memory:
      free:
        low-watermark:
          processor: 63976
