version: 0.2

phases:
  build:
    commands:
      - cd mdd
      - yamllint mdd-data
      # Save NSO rollback
      - ansible-playbook -i inventory_prod ciscops.mdd.nso_save_rollback;
      # Run data validation
      - ansible-playbook -i inventory_prod ciscops.mdd.validate;

  post_build:
    commands:
      # Load-rollback
      - ansible-playbook -i inventory_test ciscops.mdd.nso_load_rollback;

