# plugin: aws_ec2

# regions:
#   - us-gov-west-1

# filters:
#   tag:Name: uno-dev-*  # Adjust the filter to match your naming pattern


# hostnames:
#   - tag:Name
# compose:
#   ansible_host: private_ip_address

