all:
  vars:
    ansible_user: "{{ lookup('env', 'NSO_DEVICES_USERNAME') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'NSO_DEVICES_PASSWORD') | default('cisco', true) }}"
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - division
      - brigade
      - battalion
      - company
    regions:
      - org
      - us
  children:
    network:
      children:
        routers:
          children:
            division_routers:
              hosts:
                uno-dev-division-router:
                  ansible_host: 172.23.0.4
            brigade_routers:
              hosts:
                uno-dev-brigade-router:
                  ansible_host: 172.23.1.4
            battalion_routers:
              hosts:
                uno-dev-uk-battalion-router:
                  ansible_host: 172.23.3.4
                uno-dev-us-battalion-router:
                  ansible_host: 172.23.2.4
            company_routers:
              hosts:
                # uno-dev-uk-company-router:
                #   ansible_host: 172.23.5.4
                uno-dev-us-company-router:
                  ansible_host: 172.23.4.4
    org:
      children:
        us:
          children:
            division:
              hosts:
                uno-dev-division-router:
                  tags:
                    - division
                    - router
                    - stig
            brigade:
              hosts:
                uno-dev-brigade-router:
                  tags:
                    - brigade
                    - router
                    - stig
            battalion:
              hosts:
                uno-dev-us-battalion-router:
                  tags:
                    - battalion
                    - router
                    - stig
                uno-dev-uk-battalion-router:
                  tags:
                    - battalion
                    - router
                    - stig
            company:
              hosts:
                uno-dev-us-company-router:
                  tags:
                    - company
                    - router
                    - stig
                # uno-dev-uk-company-router:
                #   tags:
                #     - company
                #     - router
                #     - stig
