name: CI-pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  rollback:
    runs-on: self-hosted
    environment: army-uno
    concurrency: army-uno
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2

      - name: Run YAMLLINT in mdd-data
        run: |
          cd mdd/mdd-data
          yamllint .
      
      - name: Save Rollback
        run:  |
          cd mdd
          ansible-playbook ciscops.mdd.nso_save_rollback

      - name: Upload Rollback File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rollback-file
          path: mdd/rollback.yml
  
  validate:
    runs-on: self-hosted
    environment: army-uno
    concurrency: army-uno
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2

      - name: Data Validation
        run:  |
          cd mdd
          ansible-playbook ciscops.mdd.validate