name: CI-pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    environment: army-uno
    concurrency: army-uno
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2

      - name: Run YAMLLINT in mdd-data
        run: |
          cd mdd/mdd-data
          yamllint .
      
      - name: Save Rollback
        run:  |
          cd mdd
          ansible-playbook ciscops.mdd.nso_save_rollback
