name: CI-pipeline

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - './mdd/mdd-data/**.yml'
      - './mdd/mdd-data/**.yaml'


jobs:
  test:
    runs-on: self-hosted
    environment: army-uno
    concurrency: army-uno
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2
      - name: Change directory
        run: cd mdd
      - name: Run YAMLLINT
        run: yamllint mdd-data
      - name: Save Rollback
        run: ansible-playbook ciscops.mdd.nso_save_rollback