name: CI-pipeline

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'mdd/inventory/**'
    branches:
      - '*'

jobs:
  update-devices:
    runs-on: self-hosted
    environment: army-uno
    concurrency: army-uno
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v4

      - name: NSO Check Sync
        run: |
          cd mdd
          ansible-playbook ciscops.mdd.nso_check_sync

      - name: NSO Update Devices
        run: |
          cd mdd
          ansible-playbook ciscops.mdd.nso_update_devices
      - name: NSO sync from devices
        run: |
          cd mdd
          ansible-playbook ciscops.mdd.nso_sync_from
